"""Known test points for catchment selection tests.

Auto-generated by generate_test_data.py — DO NOT EDIT MANUALLY.
"""

TEST_POINTS = {
    "center_t1000": {
        "x": 638913.2157,
        "y": 486317.0706,
        "expected_segment_idx": 9006,
        "threshold_m2": 1000,
    },
    "center_t10000": {
        "x": 639036.9256,
        "y": 486249.6054,
        "expected_segment_idx": 9004,
        "threshold_m2": 10000,
    },
    "center_t100000": {
        "x": 639106.8395,
        "y": 486248.1803,
        "expected_segment_idx": 9003,
        "threshold_m2": 100000,
    },
    "boundary_point": {
        "x": 638873.1602,
        "y": 486142.8689,
        "threshold_m2": 1000,
        # No expected_segment_idx — any result is OK as long as not None
    },
    "outside_point": {
        "x": 600000.0,
        "y": 400000.0,
        "threshold_m2": 1000,
        "expected_segment_idx": None,
    },
    "multi_threshold": {
        "x": 639038.4307,
        "y": 486252.2675,
        "thresholds": {
            1000: 9001,
            10000: 9001,
            100000: 9001,
        },
    },
    "production_like": {
        "x": 639100.0,
        "y": 486300.0,
        "threshold_m2": 1000,
        "expected_segment_idx": 9042,
    },
}
